name: fut_chemistry
description: Optimize your FUT Squad chemistry

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.1.2
  fluttertoast: ^8.1.1
  interpolation: ^2.1.2
  equatable: ^2.0.5
  csv: ^5.0.1
  http: ^0.13.5
  flutter_launcher_icons: "^0.11.0"
  responsive_framework: ^0.2.0
  firebase_analytics: ^10.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  cached_network_image: ^3.2.3
  google_mobile_ads: ^2.3.0

dev_dependencies:
  rename: ^2.0.1
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/field_squad.png
    - assets/img/nations/
    - assets/img/leagues/
    - assets/img/clubs/small/
    - assets/img/filters/
    - assets/img/filters/rarity/
    - assets/img/filters/rarity/small_rarity/
    - assets/img/filters/clubs/large/
    - assets/img/filters/clubs/small/
    - assets/img/filters/position/
    - assets/data/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_channel: true
  image_path: "assets/icons/fut_chem_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/fut_chem_icon.png"
    background_color: "#2196f3"
    theme_color: "#2196f3"