name: share_admob
description: My new share widgets
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.0.1
  plugin_platform_interface: ^2.0.2
  # share_shimmer:
  #   path: ../share_shimmer

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
